/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hp.menu;

//import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Admin
 */
public class MenuDrop extends javax.swing.JPanel {

    /**
     * Creates new form MenuDrop
     */
    public MenuDrop() {
        initComponents();
    }
//    private MenuEvent event;
//    private MigLayout layout;
//    private String[][] menuItems = new String[][]{
//        {"Dashboard"},
//        {"Email", "Inbox", "Read", "Compost"},
//        {"Chat"},
//        {"Calendar"},
//        {"UI Kit", "Accordion", "Alerts", "Badges", "Breadcrumbs", "Buttons", "Button group"},
//        {"Advanced UI", "Cropper", "Owl Carousel", "Sweet Alert"},
//        {"Forms", "Basic Elements", "Advanced Elements", "SEditors", "Wizard"},
//        {"Charts", "Apex", "Flot", "Peity", "Sparkline"},
//        {"Table", "Basic Tables", "Data Table"},
//        {"Icons", "Feather Icons", "Flag Icons", "Mdi Icons"},
//        {"Special Pages", "Blank page", "Faq", "Invoice", "Profile", "Pricing", "Timeline"}
//    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
